# docs: http://www.appveyor.com/docs/appveyor-yml
# software installed on build machines: http://www.appveyor.com/docs/installed-software

version: 3.1.{build}

image: Visual Studio 2017
shallow_clone: true # reduce traffic

branches:
  only:
    - master

# set env var when running in appveyor so that we can distinguish
# from running locally
environment:
  inappveyor: 1

# https://github.com/appveyor/ci/issues/899
clone_script:
  - cmd: git clone -q --depth 1 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

skip_tags: true

build_script:
  - scripts\appveyor-build.bat

test_script:
  - rel64\test_util.exe

artifacts:
  - path: rel64\SumatraPDF.exe
  - path: rel64\Installer.exe
  - path: rel64\SumatraPDF.pdb.lzsa
